python regdb_train.py --dataset regdb --gpu 0 --trial 1
python regdb_train.py --dataset regdb --gpu 0 --trial 2
python regdb_train.py --dataset regdb --gpu 0 --trial 3
python regdb_train.py --dataset regdb --gpu 0 --trial 4
python regdb_train.py --dataset regdb --gpu 0 --trial 5
python regdb_train.py --dataset regdb --gpu 0 --trial 6
python regdb_train.py --dataset regdb --gpu 0 --trial 7
python regdb_train.py --dataset regdb --gpu 0 --trial 8
python regdb_train.py --dataset regdb --gpu 0 --trial 9
python regdb_train.py --dataset regdb --gpu 0 --trial 10
